"""initial db3

Revision ID: 703f310ba908
Revises: 8d8002f0c6c9
Create Date: 2025-07-12 12:51:44.630602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703f310ba908'
down_revision: Union[str, Sequence[str], None] = '8d8002f0c6c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users1',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name1', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name1')
    )
    # ### end Alembic commands ###
